### ISSUE TITLE
401 при отправке запроса на HA или nginx

### ISSUE THREAD

**Issue by kamulchik** [andvikt/mega_addon#1]
Здравствуйте!
Не уверен что это относится к аддону, но именно через nginx хорошо видны ответы. Да и я так понимаю после аддона и добавления функционала имитация http ответа это появилось.
nginx version: nginx/1.18.0 
v0.4.2 версия mega_hacs

```
server { # simple reverse-proxy
    listen       8124;
    chunked_transfer_encoding off;
    error_log /var/log/nginx/mega debug;
    location / {
      proxy_pass      http://192.168.1.200:8123/;
    }
  }
```
Настройки mega:
![image](https://user-images.githubusercontent.com/13658089/108518611-d0b62600-72d9-11eb-851c-9f530390097f.png)
Настройки интеграции:
В логах nginx:
```
192.168.1.14 - - [19/Feb/2021:17:39:11 +0300] "GET /mega?pt=3&click=1&cnt=19&mdid=mega HTTP/1.1" 401 0 "-" "megad"
192.168.1.14 - - [19/Feb/2021:17:39:11 +0300] "GET /mega?pt=11&mdid=mega&v=1 HTTP/1.1" 401 0 "-" "megad"
192.168.1.14 - - [19/Feb/2021:17:39:57 +0300] "GET /mega?pt=32&cnt=1&mdid=mega HTTP/1.1" 401 0 "-" "megad"
192.168.1.14 - - [19/Feb/2021:17:39:58 +0300] "GET /mega?pt=12&mdid=mega&v=0 HTTP/1.1" 401 0 "-" "megad"
192.168.1.14 - - [19/Feb/2021:17:40:08 +0300] "GET /mega?pt=12&mdid=mega&v=180 HTTP/1.1" 401 0 "-" "megad"
192.168.1.14 - - [19/Feb/2021:17:40:08 +0300] "GET /mega?pt=3&m=1&cnt=19&mdid=mega HTTP/1.1" 401 0 "-" "megad"
192.168.1.14 - - [19/Feb/2021:17:42:44 +0300] "GET /mega?pt=3&click=1&cnt=20&mdid=mega HTTP/1.1" 401 0 "-" "megad"
192.168.1.14 - - [19/Feb/2021:17:42:44 +0300] "GET /mega?pt=11&mdid=mega&v=0 HTTP/1.1" 401 0 "-" "megad"
```
![image](https://user-images.githubusercontent.com/13658089/108518757-fe02d400-72d9-11eb-8301-e8d7bf51270a.png)
```
curl -vvv  "http://192.168.1.200:8124/mega?pt=12&mdid=mega&v=180"
*   Trying 192.168.1.200:8124...
* TCP_NODELAY set
* Connected to 192.168.1.200 (192.168.1.200) port 8124 (#0)
> GET /mega?pt=12&mdid=mega&v=180 HTTP/1.1
> Host: 192.168.1.200:8124
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Server: nginx/1.18.0 (Ubuntu)
< Date: Fri, 19 Feb 2021 14:44:08 GMT
< Content-Type: application/octet-stream
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host 192.168.1.200 left intact

```
И при этом:
```
curl -vvv  "http://192.168.1.200:8123/mega?pt=12&mdid=mega&v=180"
*   Trying 192.168.1.200:8123...
* TCP_NODELAY set
* Connected to 192.168.1.200 (192.168.1.200) port 8123 (#0)
> GET /mega?pt=12&mdid=mega&v=180 HTTP/1.1
> Host: 192.168.1.200:8123
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Length: 0
< Content-Type: application/octet-stream
< Date: Fri, 19 Feb 2021 14:44:39 GMT
< Server: Python/3.8 aiohttp/3.7.3
< 
* Connection #0 to host 192.168.1.200 left intact
```

**Comment by andvikt** [comment]
У вас еще в логах ha должны быть ворнинги о несанкционированных попытках входа ) видимо на разных системах локальный ip поразному определяется

**Comment by andvikt** [comment]
Этот ip надо добавить в allow_hosts в yaml

**Comment by andvikt** [comment]
И да если у вас nginx свой и он на другом хосте, то соответсвенно ha будет его посылать ) пока вы не добавите в его список разрешенных. Это сделано ради вашей безопасности ) потому что авторизации на этом api нет по понятным причинам (мега не сможет авторизоваться), но при этом если он будет открыт наружу, то любой желающий сможет вас потроллить )

**Comment by kamulchik** [comment]
А проведите пожалуйста слепого за ручку (я в документацию внесу, обещаю), а то пробовал 
```
http:
  trusted_proxies:
    - 192.168.1.200

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.0/24
```
 - не прокатило. Да, nginx свой, но на там же где и HA.

**Comment by andvikt** [comment]
Это уже есть в доках, но не очевидно.
И кстати я уже добавил в веб-интерфейс эту настройку, в след версии будет

![image](https://user-images.githubusercontent.com/39195436/108540972-f13eaa00-72f2-11eb-99c6-eb4765836681.png)

**Comment by andvikt** [comment]
Кстати хорошая тема про auth_providers

Не знал про эту возможность, можно будет отказаться от моего костыля с allow_hosts

**Comment by kamulchik** [comment]
После добавление allow_hosts:
```
curl -vvv -X GET 'http://192.168.1.200:8124/mega?pt=5&m=1'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 192.168.1.200:8124...
* TCP_NODELAY set
* Connected to 192.168.1.200 (192.168.1.200) port 8124 (#0)
> GET /mega?pt=5&m=1 HTTP/1.1
> Host: 192.168.1.200:8124
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Server: nginx/1.18.0 (Ubuntu)
< Date: Sat, 20 Feb 2021 13:57:54 GMT
< Content-Type: application/octet-stream
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host 192.168.1.200 left intact
```
Добавлял так:
```
## название интеграции
mega:       
# общие настройки интеграции
 allow_hosts:
     - 192.168.1.200
# настройки относящиеся к первой меге
 mega:
#    force_d: true
#    def_response: >-
#      {% if m in [0, 1] %}d{% endif %}
#    21:
#      response_template: "7:2"
    26: #Пол детская
```

**Comment by andvikt** [comment]
А что в логе ha?

**Comment by andvikt** [comment]
И я что-то не пойму, вы curl откуда делаете? Тоже с 192.168.1.200?

И вообще, почему бы не поставить аддон? Или у вас не ha os?

Просто у меня с аддоном и os все ок из коробки, без дополнительных allow hosts

**Comment by andvikt** [comment]
Вобщем у вас там докер как я понял. Я бы вам посоветовал и nginx и ha запускать с сетью host, если запускаете через docker run, то надо добавить docker run --network host, если в docker-compose то добавить оцию network_mode: host к каждому контейнеру.
Иначе у вас там путаница кто в каких сетях, у кого какие ip адреса ) а вообще я тоже поначалу мучался с этим докером, плюнул и поставил виртуалку с ha os и бед не знаю и вам того же советую: там есть аддоны на любые случаи жизни, которые максимально лояльно к пользователю сделаны.

**Comment by andvikt** [comment]
выпустил новую бету интеграции v0.4.3b1, там можно в настройках в интерфейсе вообще отключить защиту.
Тогда вы сами в своем nginx придумайте как защитить /mega от доступа извне, в целом это должно быть очень просто, но я не очень разбираюсь в nginx - не подскажу.

**Comment by kamulchik** [comment]
Обновился до 0.4.3b1. 
Отключил защиту. В логах HA:
```
2021-02-20 20:23:15 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: mega
2021-02-20 20:24:15 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: mega
```
И по прежнему 400, напрямую не через nginx тоже 400.
Запросов от mega в логах HA нет вообще, что естественно ибо 400.
HA у меня в контейнере. 
 HA OS поставить не могу. Т.к. машина где ha - полноценная ubuntu с такими свистелками как kodi, nextcloud и прочее, что HA OS мне не даст, а на RPi B3+ никакой стабильности в работе. И на os стоит уже nginx из репозиториев, поэтому ещё один контейнер.... ну я подумаю. За функционал с отключением "безопасности" огромное спасибо, я всё равно за 2-умя NAT сижу. Curl я делал с того же хоста где и HA и nginx, его ip 192.168.1.200
Но интересно то, что если делать с другого хоста из той же подсети что mega и HA то:
`curl -vvv "http://192.168.1.200:8124/mega?pt=5&m=1"
*   Trying 192.168.1.200...
* TCP_NODELAY set
* Connected to 192.168.1.200 (192.168.1.200) port 8124 (#0)
> GET /mega?pt=5&m=1 HTTP/1.1
> Host: 192.168.1.200:8124
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Server: nginx/1.18.0 (Ubuntu)
< Date: Sat, 20 Feb 2021 17:40:17 GMT
< Content-Type: application/octet-stream
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host 192.168.1.200 left intact

curl -vvv "http://192.168.1.200:**8123**/mega?pt=5&m=1"
*   Trying 192.168.1.200...
* TCP_NODELAY set
* Connected to 192.168.1.200 (192.168.1.200) port 8123 (#0)
> GET /mega?pt=5&m=1 HTTP/1.1
> Host: 192.168.1.200:8123
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Content-Length: 0
< Content-Type: application/octet-stream
< Date: Sat, 20 Feb 2021 17:40:21 GMT
< Server: Python/3.8 aiohttp/3.7.3
< 
* Connection #0 to host 192.168.1.200 left intact

`

**Comment by andvikt** [comment]
![image](https://user-images.githubusercontent.com/39195436/108604040-848fe200-73bc-11eb-921c-c0c478113fe0.png)

**Comment by andvikt** [comment]
И это просто скрин одной страницы, реально там уже под 50 аддонов.

Просто аддон сделать очень просто-это обычные докерконтейнеры, с небольшими улучшайщерами вроде конфига в интерфейсе и так же пробросом ui приложения так же в интерфейс ha

Свистелок там столько ) что есть вообще все, все что имеет хоть какуюто ценность. И это только офиц коммьюнити стор, а еще кулибины вроде меня делают все остальное

У меня так же в убунте на виртуальной машине virtualbox все стоит. Удивительно что на сайте ha не пиарят всю крутизну их аддонов, они реально заменяют любой nas

**Comment by andvikt** [comment]
Кстати 400 ошибка это по идее не про мою интеграцию, у меня только 401 поднимается. Уберите все auth_providers свои, может они мешают.

Но вобщем я как мог помог, дальше советую все же поставить ha os, поверьте там куча преимуществ как по части самого ha (система бекапа например там толковая), так и по части остальных свистелок.

**Comment by kamulchik** [comment]
Если в конфиге так (и больше никаких упоминаний о mega):
```
mega:
# общие настройки интеграции
 allow_hosts:
     - 192.168.1.104
     - 192.168.1.200
```
То Invalid config for [mega]: required key not provided @ data['mega'][<class 'str'>]. Got None. (See /config/configuration.yaml, line 21). 
Component error: automat - Integration 'automat' not found.

Но если так:

```
mega:
 allow_hosts:
     - 192.168.1.104
     - 192.168.1.200
 mega:
    26: #Пол детская
      conv_template: >
       {% if value | float >= 85 %}
        unknown
       {% elif value | float <= -20 %}
        unknown
       {% elif value | float == 0 %}
        unknown
       {% else %}
        {{ value }}
        {% endif %}
```
То проверка конфига проходит.
Так и должно быть?

**Comment by andvikt** [comment]
Нет, не должно быть так.

**Comment by kamulchik** [comment]
Нашёл...
```
hub: 'h.MegaD' = hass.data.get(DOMAIN).get(request.remote)  # TODO: проверить какой remote
        if hub is None and request.remote == '::1':
            hub = hass.data.get(DOMAIN).get('__def')
        if hub is None:
            return Response(status=400)
```
Поменял 400, на 403, отдаёт 403.

**Comment by andvikt** [comment]
Все я понял )) блин, это надо подумать как вылечить. По сути что происходит: из-за того что это прокси, неясно какая мега обращается. А это ключевая вещь: важно понимать какая именно мега стучится. Надо на стороне прокси заголовок добавлять с оригинальным адресом. Ну и соответсвенно его обрабатывать. Сегодня я вряд ли буду у компа, завтра сделаю

**Comment by kamulchik** [comment]
Не прокси, я nginx остановил. ПРосто напрямую на 8123 шлю.

**Comment by andvikt** [comment]
Ну ясно ) к curl это тоже относится. Сам факт определения "какая мега шлет запрос" по ip хоста-это неправильная логика. На самом деле надо делать по mdid а еще лучше по X-Real-IP. Но я сделаю соответсвующие настройки в nginx и интеграции, чтобы определение меги шло с помощью заголовка X-Real-IP если он указан.

**Comment by kamulchik** [comment]
Так и если XFF явно записиваю в header, он всё равно не принимает значение. 
Делал так: curl -vvv -H "X-Forwarded-For: 192.168.1.200" "http://192.168.1.200:8123/mega?pt=5&m=1"
В Ваш код добавил msg с ip:
```
hub: 'h.MegaD' = hass.data.get(DOMAIN).get(request.remote)  # TODO: проверить какой remote
        if hub is None and request.remote == '::1':
            hub = hass.data.get(DOMAIN).get('__def')
        if hub is None:
            _msg = f"Hub is" + str(hub) + "Remote ip: " + str(hass.data.get(DOMAIN).get(request.remote))_
            _LOGGER.warning(msg)
            return Response(status=403)
```
А по журналам вижу remote ip none. Т.е. судя по описанию remote, он опирается именно на XFF. Я его вручную добавляю, но он не определяется. Для меня совсем не понятно как это раньше работало... ПРобовал откатиться на более раннюю версию интеграции - тоже самое.

**Comment by andvikt** [comment]
Не думаю что он опирается на заголовки в определении remote, тк это не безопасно. Это нужно написать в явном виде и принять связанные с этим риски

**Comment by andvikt** [comment]
Вобщем я понимаю как все это сделать, но пока нет времени

**Comment by andvikt** [comment]
Вот подтверждение, заголовки игнорятся по умолчанию, тк это небещопасно

![image](https://user-images.githubusercontent.com/39195436/108626325-a2af1e00-7460-11eb-866c-630ace3fefc8.png)

**Comment by kamulchik** [comment]
Да, уже нашёл. Но тогда вообще не понятно как он определяет и самое странное, как это раньше работало, а сейчас нет. Напрямую с разных хостов делаю curl, или сами меги делают запросы, всегда remote в значении none

**Comment by andvikt** [comment]
v0.4.3b2 - добавил определение меги по mdid, в настрйоках контроллера обязательно нужно указать megad-id, после чего в интеграции `обновить объекты`

**Comment by kamulchik** [comment]
Да, всё работает и через curl и через nginx, большое спасибо за помощь.
