### ISSUE TITLE
Ошибка при попытке обновится

### ISSUE THREAD

**Issue by UA-Caspar** [andvikt/mega_addon#2]
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /megad-cfg-2561.php on line 394
Warning: file_get_contents(): Failed to enable crypto in /megad-cfg-2561.php on line 394
Warning: file_get_contents(http://ab-log.ru/files/File/megad-firmware-2561/latest/megad-2561.hex): failed to open stream: operation failed in /megad-cfg-2561.php on line 394

**Comment by andvikt** [comment]
Вы уже не первый кто сегодня с этой ошибкой. Но я боюсь что-то на сервере ab-log произошло с сертификатом. Все работало нормально вчера. Просьба повторить операцию обновления пользуясь офиц инструкцией на ab-log, я думаю там будет та же ошибка

**Comment by andvikt** [comment]
Вы пробовали еще раз? Просто я только что сделал обновление у себя - все прошло штатно. Мне кажется, были какие-то проблемы на сервере прошивок ab-log

**Comment by UA-Caspar** [comment]
Прошу прощения, не было возможности ответить.
Пробовал сутра, часа 3 назад, была та же проблема.
Обновился с под виндовой утилитки пока.

**Comment by andvikt** [comment]
Странно конечно. С чем это связано. У вас на чем установлено?

**Comment by UA-Caspar** [comment]
hassio на убунте
