### ISSUE TITLE
Неправильная работа при использовании HTTPS

### ISSUE THREAD

**Issue by kasitoru** [andvikt/mega_addon#3]
Если в Home Assistant настроен HTTPS, то аддон не работает (по крайней мере, предполагаю что ошибка связана именно с этим):

> 2021/03/23 18:07:12 [error] 32#32: *33 no live upstreams while connecting to upstream, client: 192.168.1.3, server: , request: "GET /mega?pt=1&mdid=megad&v=0 HTTP/1.1", upstream: "http://localhost/mega?pt=1&mdid=megad&v=0", host: "192.168.1.2"
192.168.1.3 - - [23/Mar/2021:18:07:12 +0300] "GET /mega?pt=1&mdid=megad&v=0 HTTP/1.1" 502 157 "-" "megad"

**Comment by andvikt** [comment]
Те вы хотите сказать, что ha любой http трафик заворачивает на https?
Я честно говоря не знаю что ha вообще так умеет.
Но в любом случае, мега с https работать точно не будет, поэтому вам нужно сделать так чтобы ha работал в обоих режимах.
А вообще лучше не пользоваться https встроенным в ha, а пользоваться соответсвующими аддонами, например duckdns или этим (я лично очень его советую и сам пользуюсь) https://github.com/hassio-addons/addon-nginx-proxy-manager

**Comment by kasitoru** [comment]
Нет, ничего он не заворачивает. В аддон от меги приходит обычный HTTP, что видно в логах. А вот уже сам аддон дальше в HA перенаправить запрос не может.
Я так понимаю аддон перенаправляет в ha по http, а надо по https. Т.е. аддон должен определять, настроен ли в ha сертификат, и если да, то выполнять запрос с учетом этого. Т.е. вместо `http://localhost:8123/` использовать `https://localhost:8123/`.
Но тут возникнет еще одна проблема - так как сертификат выпускается на домен, то https запрос на localhost не пройдет. Нужно будет либо выключить проверку ssl для nginx, либо вынести настройку этого адреса в конфиг, чтобы можно было указать что то вроде `https://mydomain.ru:8123/`

**Comment by andvikt** [comment]
Боюсь вы до конца не понимаете как работает прокси.
Я честно не готов делать ликбез по этой теме, но поверьте на слово или почитайте теорию ) то что вы просите - невозможно.
Прокси перенаправляет запросы из одной точки в другую, в данном случае вы просите перенаправить http трафик на https, но в двух словах - так делать можно, но с клиентом, который поддерживает так называемый апгрейд протокола, что в случае с мегой невозможно технически.

Поэтому еще раз повторюсь - у вас есть две опции: разобраться, как сделать так, чтобы ha продолжал принимать нешифрованный трафик на http , я уверен это можно сделать и если все-таки нельзя, то ссылку на классный-супер-удобный аддон для реализации каноничного шифрования с lets encrypt я дал

с точки зрения моего аддона тут сделать к сожалению нечего.

**Comment by andvikt** [comment]
Читаю доки ha и даже понять не могу где вы нашли какой-то ручной способ установки сертификатов с последующим отключением http:// трафика

На офиц странице про ssl разрабы ha рекомендуют duckdns аддон-он идет в стандартном репо.

С ним у вас точно не отключится http://

**Comment by andvikt** [comment]
Добавил эксперимента ради еще один порт
Поставьте новую версию 0.1.3 и в меге укажите порт 8125, этот порт перенаправляет трафик на https://localhost:8123/

Но мне кажется это не сработает.

**Comment by kasitoru** [comment]
> Я честно не готов делать ликбез по этой теме, но поверьте на слово или почитайте теорию ) то что вы просите - невозможно.

Прежде чем кого то учить, начните с себя) А верить кому то на слово - дурная привычка.

> Читаю доки ha и даже понять не могу где вы нашли какой-то ручной способ установки сертификатов с последующим отключением http:// трафика

Ничего специально для этого не делал, достаточно было указать `ssl_certificate` и `ssl_key` в настройках.

> На офиц странице про ssl разрабы ha рекомендуют duckdns аддон-он идет в стандартном репо.

Судя по описанию, он занимается предоставлением динамического днс и обновлением сертификатов. Ни первое, ни второе мне не нужно.

> С ним у вас точно не отключится http://

Я не для того ssl настраивал, чтобы http оставлять)

> Но мне кажется это не сработает.

Все отлично работает, благодарю! Боялся что будет ошибка проверки сертификата, но нет.

**Comment by m637ex** [comment]
Аналогичная проблема видимо  у меня.
RasberryPi 3, armbian debian последний, home assistant последний . Стоит в Docker контейнере
До установки megad отлично работала. После установки nginx proxy manager кнопки перестали работать. Доступ настроен пока  по http. Но кнопки уже не работают. C HA свет работает. В чем может быть загвоздка?

Настроил 2 хоста: localhost на 80 порт, и домен: на порт 8123. 
В роутере пробросил 80, 443, и 8123
