### ISSUE TITLE
Unable to install update addon 

### ISSUE THREAD

**Issue by lupin-de-mid** [andvikt/mega_addon#4]
Docker image of add-on failed install every time from the beginning 
```
Step 4/15 : ENV LANG C.UTF-8
 ---> Running in c5326180bea7
Removing intermediate container c5326180bea7
 ---> 7d23848826fc
Step 5/15 : RUN mkdir -p /usr/src/bashio     && apk add --no-cache bash jq     && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz"         | tar -xzf - --strip 1 -C /usr/src/bashio     && mv /usr/src/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && docker-php-ext-install sockets

--> Running in c704543e1813
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
ERROR: unable to select packages:

  bash (no such package):
    required by: world[bash]
  jq (no such package):
    required by: world[jq]
Removing intermediate container c704543e1813

21-04-11 20:27:57 ERROR (MainThread) [supervisor.jobs] Unhandled exception: '50f4faee_megad-updater'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 520, in _build
    image, log = self.sys_docker.images.build(
  File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c mkdir -p /usr/src/bashio     && apk add --no-cache bash jq     && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz"         | tar -xzf - --strip 1 -C /usr/src/bashio     && mv /usr/src/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio     && docker-php-ext-install sockets' returned a non-zero code: 2
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 181, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 504, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 530, in _build
    _LOGGER.error("Can't build %s:%s: %s", self.image, version, err)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 60, in image
    return self.addon.image
```

**Comment by andvikt** [comment]
Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

А вы пробовали еще раз?

У меня ошибка не воспроизводится. Как вариант, у вас из сети не доступен dl-cdn.alpinelinux.org

**Comment by lupin-de-mid** [comment]
Я пробую раз в пару недель, еще ни разу не встал
Проверил прямо с малины   - доступен  dl-cdn.alpinelinux.org 
Другие аддоны ставятся нормально

**Comment by andvikt** [comment]
Странная история конечно. 
Я попробую собрать готовые образы, чтобы они не собирались у вас локально.

**Comment by andvikt** [comment]
Сделал, обновите аддон до v0.3.0

**Comment by Webmonit** [comment]
У меня 0.3.1 установился, круто!

**Comment by lupin-de-mid** [comment]
Смогу только в пятницу проверить18:38, 21 апреля 2021 г., Andrew S ***@***.***>:
У меня 0.3.1 установился, круто!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Signature%20placeholder

**Comment by Webmonit** [comment]
Сделайте пожалуйста в опциях подсказки. И еще в аддонах обычно делают default. Ну и на будущее, было бы хорошо сохранять и восстанавливать конфиг. Спасибо!

**Comment by andvikt** [comment]
Подсказки есть, конфиг сохраняется )

По умолчанию апдейт делается с сохранением и восстановлением автоматически. Сохраненный конфиг так же можно найти в папке backup. 

Единственное что не сохраняется-это состояния выходов. Но этой опции нет впринципе в скрипте обновления прошивок от разработчика меги. Скрипт делает он.

Если подсказок нет, пришлите скрин. Вообще по умолчанию конфиг заполнен подсказкой.

**Comment by Webmonit** [comment]
![Confi_mega](https://user-images.githubusercontent.com/36241895/115650562-1c189f00-a332-11eb-99c4-0b4367cd118a.jpg)
У меня сейчас вот так. 
Я про папку Backup, не всегда к ней есть доступ удаленно, хотелось бы с вэб интерфейса сохранять конфиги.  Состояние выходов есть в самом HA, в плагине оно не нужно, на мой взгляд.

**Comment by andvikt** [comment]
> У меня сейчас вот так

Кстати, options надо убрать )

> Я про папку Backup, не всегда к ней есть доступ удаленно, хотелось бы с вэб интерфейса сохранять конфиги. 

Конфиги сохранять имеет смысл перед обновлением прошивки - так и происходит, если вам нужно только сохранение конфига, без обновления прошивки - можно написать options: "--read-conf /backup/megad.cfg -p sec"

> Состояние выходов есть в самом HA, в плагине оно не нужно, на мой взгляд.

Цель данного аддона - сделать обновление прошивки удобнее, причем больше наверно это ориентировано на пользователей Mac/Linux, тк под них нет графической оболочки для обновления, на винде вообще не вижу в этом смысла, тк там есть нормальная графическая утилита для обновления. )

То что просите вы - восстанавливать стейты из HA конечно технически возможно, но это уже серьезная работа, на которую у меня сейчас нет времени. В текущем виде аддон - это очень простая штука, несколько строк кода - просто запускается скрипт обновления прошивки с автоматически заполненными параметрами, ни больше ни меньше )

**Comment by Webmonit** [comment]
Аддон очень крутой, я боялся обновлять Мегу потому, что надо было быть увернным, что настройки будет можно сохранить и обновиться без короткого замыкания на нагрузке из-за неверной коммутации. Такое бывает на серьезных объектах. Даже не представляете, какое крутое устройство мы имеем! Если его сертифицировать - можно всю страну автоматизировать.

**Comment by lupin-de-mid** [comment]
Установилось, спасибо этот можно закрывать видимо
, но дальше вылез другой баг https://github.com/andvikt/mega_addon/issues/5
