### ISSUE TITLE
Бесконечное обновление.

### ISSUE THREAD

**Issue by Sheredeka** [andvikt/mega_addon#6]
MegaD-2561 by ab-log.ru (fw: 4.51b7)
HA core-2021.8.8

После установки и запуска удачно обновил прошивку до крайней. Заметил что веб-интерфейс меги тупит, НА не всегда может отправить команду. Посмотрел watchdog - ругается на проблемы, открыл лог обновлятора - и вижу, что он бесконечно прошивает и прошивает. пока не остановил процесс....

**Comment by andvikt** [comment]
А зачем вы включили watchdog? Аддон запускает один раз, устанавливает обновление и тушится. Есливы включаете watchdog, то аддон постоянно будет стартовать-для этого watchdog и придуман, но не нужно его включать для моего аддона. Кроме того не вклбчайте start on boot.

Видимо нужно написать об этом в инструкции

**Comment by Sheredeka** [comment]
Спасибо! Обязательно напишите в инструкции!!!
